
> 3DForFun@1.0.0 build D:\workspace\blog
> vuepress build .

wait Extracting site metadata...
tip Apply theme vuepress-theme-reco ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress-reco/back-to-top (i.e. "@vuepress-reco/vuepress-plugin-back-to-top") ...
tip Apply plugin @vuepress-reco/loading-page (i.e. "@vuepress-reco/vuepress-plugin-loading-page") ...
tip Apply plugin @vuepress-reco/pagation (i.e. "@vuepress-reco/vuepress-plugin-pagation") ...
tip Apply plugin @vuepress-reco/comments (i.e. "@vuepress-reco/vuepress-plugin-comments") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/blog (i.e. "@vuepress/plugin-blog") ...
tip Apply plugin smooth-scroll (i.e. "vuepress-plugin-smooth-scroll") ...
